# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: test
        run: git config --global user.email "test@example.com"
      - name: test
        run: git config --global user.name "test Name"
      - name: test
        run: git remote remove origin
      - name: test
        run: git remote add origin https://LS-ELLO:dpffhrkwhgdk0@github.com/LS-ELLO/code-review-test
        
      - name: test
        run: git checkout --orphan review-target
      - name: test
        run: git commit --allow-empty -m "Empty Commit"
      - name: test
        run: git push origin review-target
      - name: test
        run: git checkout main
      - name: test
        run: git checkout -b review
      - name: test
        run: git rebase -i review-target
      - name: test
        run: git push origin review

          
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint
                 
      # tee 는 표준 입력(standard input)에서 읽어서 표준 출력(standard output) 과 파일에 쓰는 명령어입니다. (https://www.lesstif.com/lpt/linux-tee-89556049.html)
      # 규식이형 사용
      - name: Analysing the code with pylint
        run: |
          python -m pylint --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` |
          tee pylint.txt
          
      - name: Upload pylint.txt as artifact
        uses: actions/upload-artifact@v2
        with:
          name: pylint report
          path: pylint.txt
       

